# Generated by Django 5.2.3 on 2025-08-07 05:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépenses',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du fournisseur')),
                ('type_fournisseur', models.CharField(choices=[('ENTREPRISE', 'Entreprise'), ('PARTICULIER', 'Particulier'), ('ADMINISTRATION', 'Administration')], max_length=20, verbose_name='Type')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('numero_compte', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de compte')),
                ('banque', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banque')),
                ('numero_nif', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro NIF')),
                ('numero_rccm', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro RCCM')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=50, verbose_name='Numéro de facture')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('description', models.TextField(verbose_name='Description')),
                ('type_depense', models.CharField(choices=[('FONCTIONNEMENT', 'Fonctionnement'), ('INVESTISSEMENT', 'Investissement'), ('PERSONNEL', 'Personnel'), ('MAINTENANCE', 'Maintenance'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de dépense')),
                ('montant_ht', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Montant HT (GNF)')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Taux TVA (%)')),
                ('montant_tva', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Montant TVA (GNF)')),
                ('montant_ttc', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Montant TTC (GNF)')),
                ('date_facture', models.DateField(verbose_name='Date de facture')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée'), ('PAYEE', 'Payée'), ('REJETEE', 'Rejetée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='depenses.categoriedepense')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_creees', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_validees', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='depenses.fournisseur')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_facture', '-date_creation'],
                'unique_together': {('numero_facture', 'fournisseur')},
            },
        ),
        migrations.CreateModel(
            name='HistoriqueDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('VALIDATION', 'Validation'), ('PAIEMENT', 'Paiement'), ('REJET', 'Rejet'), ('ANNULATION', 'Annulation')], max_length=20, verbose_name='Action')),
                ('description', models.TextField(verbose_name='Description')),
                ('ancien_statut', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ancien statut')),
                ('nouveau_statut', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nouveau statut')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='depenses.depense')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique dépense',
                'verbose_name_plural': 'Historiques dépenses',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='PieceJustificative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(choices=[('FACTURE', 'Facture'), ('RECU', 'Reçu'), ('BON_COMMANDE', 'Bon de commande'), ('BON_LIVRAISON', 'Bon de livraison'), ('DEVIS', 'Devis'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de pièce')),
                ('nom_fichier', models.CharField(max_length=200, verbose_name='Nom du fichier')),
                ('fichier', models.FileField(upload_to='depenses/pieces/', verbose_name='Fichier')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_justificatives', to='depenses.depense')),
                ('uploade_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pièce justificative',
                'verbose_name_plural': 'Pièces justificatives',
            },
        ),
        migrations.CreateModel(
            name='BudgetAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('budget_prevu', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Budget prévu (GNF)')),
                ('budget_engage', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Budget engagé (GNF)')),
                ('budget_consomme', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Budget consommé (GNF)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='depenses.categoriedepense')),
            ],
            options={
                'verbose_name': 'Budget annuel',
                'verbose_name_plural': 'Budgets annuels',
                'ordering': ['-annee', 'categorie__nom'],
                'unique_together': {('annee', 'categorie')},
            },
        ),
    ]
