# Generated by Django 5.2.5 on 2025-09-09 05:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('relation', models.CharField(choices=[('PERE', 'Père'), ('MERE', 'Mère'), ('TUTEUR', 'Tuteur'), ('TUTRICE', 'Tutrice'), ('GRAND_PERE', 'Grand-père'), ('GRAND_MERE', 'Grand-mère'), ('ONCLE', 'Oncle'), ('TANTE', 'Tante'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Relation')),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+224\\d{8,9}$', 'Format: +224XXXXXXXXX')], verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
            },
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'école")),
                ('nom_complet', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nom complet officiel')),
                ('slug', models.SlugField(default='ecole-default', max_length=200, unique=True, verbose_name='Identifiant URL')),
                ('type_ecole', models.CharField(choices=[('PUBLIQUE', 'École Publique'), ('PRIVEE', 'École Privée'), ('CONFESSIONNELLE', 'École Confessionnelle'), ('INTERNATIONALE', 'École Internationale')], default='PRIVEE', max_length=20, verbose_name="Type d'école")),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('ville', models.CharField(default='Conakry', max_length=100, verbose_name='Ville')),
                ('prefecture', models.CharField(default='Conakry', max_length=100, verbose_name='Préfecture')),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+224\\d{8,9}$', 'Format: +224XXXXXXXXX')], verbose_name='Téléphone')),
                ('telephone_2', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+224\\d{8,9}$', 'Format: +224XXXXXXXXX')], verbose_name='Téléphone 2')),
                ('email', models.EmailField(default='contact@ecole.com', max_length=254, verbose_name='Email officiel')),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('directeur', models.CharField(max_length=100, verbose_name='Directeur/Directrice')),
                ('directeur_telephone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+224\\d{8,9}$', 'Format: +224XXXXXXXXX')], verbose_name='Téléphone directeur')),
                ('directeur_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email directeur')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ecoles/logos/', verbose_name='Logo')),
                ('couleur_principale', models.CharField(default='#1976d2', max_length=7, verbose_name='Couleur principale (hex)')),
                ('couleur_secondaire', models.CharField(default='#424242', max_length=7, verbose_name='Couleur secondaire (hex)')),
                ('numero_autorisation', models.CharField(blank=True, max_length=100, null=True, verbose_name="N° d'autorisation")),
                ('date_autorisation', models.DateField(blank=True, null=True, verbose_name="Date d'autorisation")),
                ('ministere_tutelle', models.CharField(default="Ministère de l'Éducation Nationale", max_length=200, verbose_name='Ministère de tutelle')),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDUE', 'Suspendue'), ('EN_ATTENTE', 'En attente de validation'), ('FERMEE', 'Fermée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_activation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'activation")),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('devise', models.CharField(default='GNF', max_length=10, verbose_name='Devise')),
                ('fuseau_horaire', models.CharField(default='Africa/Conakry', max_length=50, verbose_name='Fuseau horaire')),
                ('langue_principale', models.CharField(default='fr', max_length=10, verbose_name='Langue principale')),
                ('notes_admin', models.TextField(blank=True, null=True, verbose_name='Notes administratives')),
                ('utilisateur_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecole_administree', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur principal')),
            ],
            options={
                'verbose_name': 'École',
                'verbose_name_plural': 'Écoles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la classe')),
                ('niveau', models.CharField(choices=[('GARDERIE', 'Garderie'), ('MATERNELLE', 'Maternelle'), ('PRIMAIRE_1', 'Primaire 1ère'), ('PRIMAIRE_2', 'Primaire 2ème'), ('PRIMAIRE_3', 'Primaire 3ème'), ('PRIMAIRE_4', 'Primaire 4ème'), ('PRIMAIRE_5', 'Primaire 5ème'), ('PRIMAIRE_6', 'Primaire 6ème'), ('COLLEGE_7', 'Collège 7ème'), ('COLLEGE_8', 'Collège 8ème'), ('COLLEGE_9', 'Collège 9ème'), ('COLLEGE_10', 'Collège 10ème'), ('LYCEE_11', 'Lycée 11ème'), ('LYCEE_12', 'Lycée 12ème'), ('TERMINALE', 'Terminale')], max_length=20, verbose_name='Niveau')),
                ('code_matricule', models.CharField(blank=True, help_text='Préfixe utilisé pour les matricules (ex: PN3, CN7, L11SL).', max_length=12, null=True, verbose_name='Code matricule')),
                ('annee_scolaire', models.CharField(help_text='Format: 2024-2025', max_length=9, verbose_name='Année scolaire')),
                ('capacite_max', models.PositiveIntegerField(default=30, verbose_name='Capacité maximale')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='eleves.ecole')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='eleves/photos/', verbose_name='Photo')),
                ('date_inscription', models.DateField(verbose_name="Date d'inscription")),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('EXCLU', 'Exclu'), ('TRANSFERE', 'Transféré'), ('DIPLOME', 'Diplômé')], db_index=True, default='ACTIF', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='eleves.classe')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('responsable_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleves_principal', to='eleves.responsable', verbose_name='Responsable principal')),
                ('responsable_secondaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves_secondaire', to='eleves.responsable', verbose_name='Responsable secondaire')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='GrilleTarifaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('GARDERIE', 'Garderie'), ('MATERNELLE', 'Maternelle'), ('PRIMAIRE_1', 'Primaire 1ère'), ('PRIMAIRE_2', 'Primaire 2ème'), ('PRIMAIRE_3', 'Primaire 3ème'), ('PRIMAIRE_4', 'Primaire 4ème'), ('PRIMAIRE_5', 'Primaire 5ème'), ('PRIMAIRE_6', 'Primaire 6ème'), ('COLLEGE_7', 'Collège 7ème'), ('COLLEGE_8', 'Collège 8ème'), ('COLLEGE_9', 'Collège 9ème'), ('COLLEGE_10', 'Collège 10ème'), ('LYCEE_11', 'Lycée 11ème'), ('LYCEE_12', 'Lycée 12ème'), ('TERMINALE', 'Terminale')], max_length=20, verbose_name='Niveau')),
                ('annee_scolaire', models.CharField(max_length=9, verbose_name='Année scolaire')),
                ('frais_inscription', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name="Frais d'inscription (GNF)")),
                ('tranche_1', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name='1ère tranche (GNF)')),
                ('tranche_2', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name='2ème tranche (GNF)')),
                ('tranche_3', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name='3ème tranche (GNF)')),
                ('periode_1', models.CharField(default="À l'inscription", max_length=50, verbose_name='Période 1')),
                ('periode_2', models.CharField(default='Début janvier', max_length=50, verbose_name='Période 2')),
                ('periode_3', models.CharField(default='Début mars', max_length=50, verbose_name='Période 3')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grilles_tarifaires', to='eleves.ecole')),
            ],
            options={
                'verbose_name': 'Grille tarifaire',
                'verbose_name_plural': 'Grilles tarifaires',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('CHANGEMENT_CLASSE', 'Changement de classe'), ('CHANGEMENT_STATUT', 'Changement de statut'), ('SUSPENSION', 'Suspension'), ('EXCLUSION', 'Exclusion'), ('TRANSFERT', 'Transfert')], max_length=20, verbose_name='Action')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='eleves.eleve')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique élève',
                'verbose_name_plural': 'Historiques élèves',
                'ordering': ['-date_action'],
            },
        ),
        migrations.AddIndex(
            model_name='ecole',
            index=models.Index(fields=['statut'], name='eleves_ecol_statut_4e73b9_idx'),
        ),
        migrations.AddIndex(
            model_name='ecole',
            index=models.Index(fields=['slug'], name='eleves_ecol_slug_da29d2_idx'),
        ),
        migrations.AddIndex(
            model_name='ecole',
            index=models.Index(fields=['ville', 'prefecture'], name='eleves_ecol_ville_a0f511_idx'),
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['ecole', 'niveau'], name='eleves_clas_ecole_i_48e73d_idx'),
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['ecole', 'annee_scolaire'], name='eleves_clas_ecole_i_7e04dc_idx'),
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['ecole', 'code_matricule'], name='eleves_clas_ecole_i_ace8a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('ecole', 'nom', 'annee_scolaire')},
        ),
        migrations.AlterUniqueTogether(
            name='grilletarifaire',
            unique_together={('ecole', 'niveau', 'annee_scolaire')},
        ),
        migrations.AddIndex(
            model_name='eleve',
            index=models.Index(fields=['classe', 'statut'], name='eleves_elev_classe__cbf5c7_idx'),
        ),
        migrations.AddIndex(
            model_name='eleve',
            index=models.Index(fields=['nom', 'prenom'], name='eleves_elev_nom_dcb60d_idx'),
        ),
        migrations.AddIndex(
            model_name='eleve',
            index=models.Index(fields=['date_inscription'], name='eleves_elev_date_in_c9268c_idx'),
        ),
    ]
