# Generated by Django 5.2.3 on 2025-08-19 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('EXCLU', 'Exclu'), ('TRANSFERE', 'Transféré'), ('DIPLOME', 'Diplômé')], db_index=True, default='ACTIF', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['ecole', 'niveau'], name='eleves_clas_ecole_i_48e73d_idx'),
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['ecole', 'annee_scolaire'], name='eleves_clas_ecole_i_7e04dc_idx'),
        ),
        migrations.AddIndex(
            model_name='eleve',
            index=models.Index(fields=['classe', 'statut'], name='eleves_elev_classe__cbf5c7_idx'),
        ),
        migrations.AddIndex(
            model_name='eleve',
            index=models.Index(fields=['nom', 'prenom'], name='eleves_elev_nom_dcb60d_idx'),
        ),
        migrations.AddIndex(
            model_name='eleve',
            index=models.Index(fields=['date_inscription'], name='eleves_elev_date_in_c9268c_idx'),
        ),
    ]
