# Generated by Django 5.2.3 on 2025-08-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0002_alter_eleve_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='code_matricule',
            field=models.CharField(blank=True, help_text='Préfixe utilisé pour les matricules (ex: PN3, CN7, L11SL).', max_length=12, null=True, verbose_name='Code matricule'),
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['ecole', 'code_matricule'], name='eleves_clas_ecole_i_ace8a7_idx'),
        ),
    ]
