# Generated by Django 5.2.3 on 2025-08-07 05:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du mode')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('frais_supplementaires', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name='Frais supplémentaires (GNF)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Mode de paiement',
                'verbose_name_plural': 'Modes de paiements',
            },
        ),
        migrations.CreateModel(
            name='TypePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Type de paiement',
                'verbose_name_plural': 'Types de paiements',
            },
        ),
        migrations.CreateModel(
            name='EcheancierPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=9, verbose_name='Année scolaire')),
                ('frais_inscription_du', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name="Frais d'inscription dus (GNF)")),
                ('tranche_1_due', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name='1ère tranche due (GNF)')),
                ('tranche_2_due', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name='2ème tranche due (GNF)')),
                ('tranche_3_due', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name='3ème tranche due (GNF)')),
                ('date_echeance_inscription', models.DateField(verbose_name='Échéance inscription')),
                ('date_echeance_tranche_1', models.DateField(verbose_name='Échéance 1ère tranche')),
                ('date_echeance_tranche_2', models.DateField(verbose_name='Échéance 2ème tranche')),
                ('date_echeance_tranche_3', models.DateField(verbose_name='Échéance 3ème tranche')),
                ('frais_inscription_paye', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name="Frais d'inscription payés (GNF)")),
                ('tranche_1_payee', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name='1ère tranche payée (GNF)')),
                ('tranche_2_payee', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name='2ème tranche payée (GNF)')),
                ('tranche_3_payee', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name='3ème tranche payée (GNF)')),
                ('statut', models.CharField(choices=[('A_PAYER', 'À payer'), ('PAYE_PARTIEL', 'Payé partiellement'), ('PAYE_COMPLET', 'Payé complètement'), ('EN_RETARD', 'En retard')], default='A_PAYER', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='echeancier', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Échéancier de paiement',
                'verbose_name_plural': 'Échéanciers de paiements',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recu', models.CharField(max_length=20, unique=True, verbose_name='Numéro de reçu')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant (GNF)')),
                ('date_paiement', models.DateField(verbose_name='Date de paiement')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('REMBOURSE', 'Remboursé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('reference_externe', models.CharField(blank=True, help_text='Numéro de transaction Mobile Money, chèque, etc.', max_length=100, null=True, verbose_name='Référence externe')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_crees', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='eleves.eleve')),
                ('mode_paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paiements.modepaiement')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_valides', to=settings.AUTH_USER_MODEL)),
                ('type_paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paiements.typepaiement')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RemiseReduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la remise')),
                ('type_remise', models.CharField(choices=[('POURCENTAGE', 'Pourcentage'), ('MONTANT_FIXE', 'Montant fixe')], max_length=20, verbose_name='Type de remise')),
                ('valeur', models.DecimalField(decimal_places=2, help_text='Pourcentage (ex: 10.50) ou montant en GNF', max_digits=10, verbose_name='Valeur')),
                ('motif', models.CharField(choices=[('FRATRIE', 'Réduction fratrie'), ('MERITE', 'Réduction mérite'), ('SOCIALE', 'Réduction sociale'), ('EMPLOYEE', "Enfant d'employé"), ('AUTRE', 'Autre')], max_length=20, verbose_name='Motif')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remise/Réduction',
                'verbose_name_plural': 'Remises/Réductions',
            },
        ),
        migrations.CreateModel(
            name='PaiementRemise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_remise', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant de la remise (GNF)')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remises', to='paiements.paiement')),
                ('remise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paiements.remisereduction')),
            ],
            options={
                'verbose_name': 'Remise appliquée',
                'verbose_name_plural': 'Remises appliquées',
                'unique_together': {('paiement', 'remise')},
            },
        ),
    ]
