# Generated by Django 5.2.5 on 2025-08-18 08:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0001_initial'),
        ('paiements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'E-mail'), ('APPEL', 'Appel téléphonique'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Canal')),
                ('message', models.TextField(verbose_name='Message de relance')),
                ('statut', models.CharField(choices=[('ENREGISTREE', 'Enregistrée'), ('ENVOYEE', 'Envoyée'), ('ECHEC', 'Échec')], default='ENREGISTREE', max_length=20, verbose_name='Statut')),
                ('solde_estime', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name='Solde estimé (GNF)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relances_creees', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relances', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Relance',
                'verbose_name_plural': 'Relances',
                'ordering': ['-date_creation'],
            },
        ),
    ]
