# Generated by Django 5.2.3 on 2025-08-19 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0002_alter_eleve_statut_and_more'),
        ('paiements', '0002_relance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateField(db_index=True, verbose_name='Date de paiement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('REMBOURSE', 'Remboursé')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['eleve', 'date_paiement'], name='paiements_p_eleve_i_4ad9c8_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['eleve', 'statut'], name='paiements_p_eleve_i_3af83b_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['statut', 'date_paiement'], name='paiements_p_statut_551504_idx'),
        ),
        migrations.AddIndex(
            model_name='relance',
            index=models.Index(fields=['eleve', 'statut'], name='paiements_r_eleve_i_e03c00_idx'),
        ),
        migrations.AddIndex(
            model_name='relance',
            index=models.Index(fields=['-date_creation'], name='paiements_r_date_cr_db134d_idx'),
        ),
    ]
