# Generated by Django 5.2.5 on 2025-08-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0003_alter_paiement_date_paiement_alter_paiement_statut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioInboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('UNKNOWN', 'Inconnu')], db_index=True, default='UNKNOWN', max_length=20)),
                ('from_number', models.CharField(db_index=True, max_length=50)),
                ('to_number', models.CharField(db_index=True, max_length=50)),
                ('body', models.TextField(blank=True, null=True)),
                ('message_sid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('wa_id', models.CharField(blank=True, max_length=64, null=True)),
                ('num_media', models.IntegerField(default=0)),
                ('delivery_status', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('error_code', models.CharField(blank=True, max_length=32, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Message entrant Twilio',
                'verbose_name_plural': 'Messages entrants Twilio',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['message_sid'], name='paiements_t_message_9e35aa_idx'), models.Index(fields=['channel', 'received_at'], name='paiements_t_channel_08cacc_idx')],
            },
        ),
    ]
