# Generated by Django 5.2.5 on 2025-09-09 06:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_tete_personnalise', models.TextField(blank=True, null=True, verbose_name='En-tête personnalisé')),
                ('pied_page_personnalise', models.TextField(blank=True, null=True, verbose_name='Pied de page personnalisé')),
                ('template_fiche_inscription', models.TextField(blank=True, null=True, verbose_name="Template fiche d'inscription")),
                ('template_recu_paiement', models.TextField(blank=True, null=True, verbose_name='Template reçu de paiement')),
                ('template_bulletin_notes', models.TextField(blank=True, null=True, verbose_name='Template bulletin de notes')),
                ('template_abonnement_bus', models.TextField(blank=True, null=True, verbose_name='Template abonnement bus')),
                ('afficher_logo_documents', models.BooleanField(default=True, verbose_name='Afficher le logo sur les documents')),
                ('taille_logo_documents', models.CharField(choices=[('small', 'Petit'), ('medium', 'Moyen'), ('large', 'Grand')], default='medium', max_length=20, verbose_name='Taille du logo')),
                ('prefixe_recu', models.CharField(default='REC', max_length=10, verbose_name='Préfixe des reçus')),
                ('prefixe_facture', models.CharField(default='FAC', max_length=10, verbose_name='Préfixe des factures')),
                ('compteur_recu', models.PositiveIntegerField(default=1, verbose_name='Compteur des reçus')),
                ('compteur_facture', models.PositiveIntegerField(default=1, verbose_name='Compteur des factures')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notifications par email')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='Notifications par SMS')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ecole', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='eleves.ecole')),
            ],
            options={
                'verbose_name': "Configuration d'école",
                'verbose_name_plural': "Configurations d'écoles",
            },
        ),
        migrations.CreateModel(
            name='DemandeInscriptionEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_demandeur', models.CharField(max_length=100, verbose_name='Nom du demandeur')),
                ('prenom_demandeur', models.CharField(max_length=100, verbose_name='Prénom du demandeur')),
                ('fonction_demandeur', models.CharField(max_length=100, verbose_name="Fonction dans l'école")),
                ('email_demandeur', models.EmailField(max_length=254, verbose_name='Email du demandeur')),
                ('telephone_demandeur', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+224\\d{8,9}$', 'Format: +224XXXXXXXXX')], verbose_name='Téléphone du demandeur')),
                ('nom_ecole', models.CharField(max_length=200, verbose_name="Nom de l'école")),
                ('nom_complet_ecole', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nom complet officiel')),
                ('type_ecole', models.CharField(choices=[('PUBLIQUE', 'École Publique'), ('PRIVEE', 'École Privée'), ('CONFESSIONNELLE', 'École Confessionnelle'), ('INTERNATIONALE', 'École Internationale')], max_length=20, verbose_name="Type d'école")),
                ('adresse_ecole', models.TextField(verbose_name="Adresse de l'école")),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('prefecture', models.CharField(max_length=100, verbose_name='Préfecture')),
                ('telephone_ecole', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+224\\d{8,9}$', 'Format: +224XXXXXXXXX')], verbose_name='Téléphone principal')),
                ('email_ecole', models.EmailField(max_length=254, verbose_name="Email officiel de l'école")),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('nom_directeur', models.CharField(max_length=100, verbose_name='Nom du directeur')),
                ('telephone_directeur', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+224\\d{8,9}$', 'Format: +224XXXXXXXXX')], verbose_name='Téléphone directeur')),
                ('numero_autorisation', models.CharField(blank=True, max_length=100, null=True, verbose_name="N° d'autorisation")),
                ('date_autorisation', models.DateField(blank=True, null=True, verbose_name="Date d'autorisation")),
                ('logo_ecole', models.ImageField(blank=True, null=True, upload_to='demandes/logos/', verbose_name="Logo de l'école")),
                ('document_autorisation', models.FileField(blank=True, null=True, upload_to='demandes/documents/', verbose_name="Document d'autorisation")),
                ('autres_documents', models.FileField(blank=True, null=True, upload_to='demandes/documents/', verbose_name='Autres documents')),
                ('nombre_eleves_estime', models.PositiveIntegerField(verbose_name="Nombre d'élèves estimé")),
                ('nombre_enseignants', models.PositiveIntegerField(verbose_name="Nombre d'enseignants")),
                ('niveaux_enseignes', models.TextField(help_text='Ex: Maternelle, Primaire, Collège...', verbose_name='Niveaux enseignés')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de traitement'), ('EN_COURS', 'En cours de vérification'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée'), ('SUSPENDUE', 'Suspendue')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('commentaire_demandeur', models.TextField(blank=True, null=True, verbose_name='Commentaire du demandeur')),
                ('notes_admin', models.TextField(blank=True, null=True, verbose_name='Notes administratives')),
                ('motif_rejet', models.TextField(blank=True, null=True, verbose_name='Motif de rejet')),
                ('ecole_creee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eleves.ecole', verbose_name='École créée')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
            ],
            options={
                'verbose_name': "Demande d'inscription d'école",
                'verbose_name_plural': "Demandes d'inscription d'écoles",
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='TemplateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du template')),
                ('type_document', models.CharField(choices=[('FICHE_INSCRIPTION', "Fiche d'inscription"), ('RECU_PAIEMENT', 'Reçu de paiement'), ('BULLETIN_NOTES', 'Bulletin de notes'), ('ABONNEMENT_BUS', 'Abonnement bus'), ('CERTIFICAT_SCOLARITE', 'Certificat de scolarité'), ('RELEVE_NOTES', 'Relevé de notes')], max_length=30, verbose_name='Type de document')),
                ('contenu_html', models.TextField(verbose_name='Contenu HTML')),
                ('styles_css', models.TextField(blank=True, null=True, verbose_name='Styles CSS')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('est_par_defaut', models.BooleanField(default=False, verbose_name='Template par défaut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eleves.ecole', verbose_name='École (null = template par défaut)')),
            ],
            options={
                'verbose_name': 'Template de document',
                'verbose_name_plural': 'Templates de documents',
                'unique_together': {('type_document', 'ecole', 'est_par_defaut')},
            },
        ),
    ]
