# Generated by Django 5.2.5 on 2025-09-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_ecoles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeinscriptionecole',
            name='code_acces',
            field=models.CharField(blank=True, help_text="Code généré par l'administrateur pour créer le compte", max_length=50, null=True, unique=True, verbose_name="Code d'accès"),
        ),
    ]
