# Generated by Django 5.2.5 on 2025-09-09 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_ecoles', '0002_demandeinscriptionecole_code_acces'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeinscriptionecole',
            name='utilisateur_cree',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_inscription', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur créé'),
        ),
    ]
