# Generated by Django 5.2.6 on 2025-09-09 16:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription_ecoles', '0003_demandeinscriptionecole_utilisateur_cree'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcheancierInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(help_text='Format: 2024-2025', max_length=9, verbose_name='Année scolaire')),
                ('date_echeance_inscription', models.DateField(help_text="Date limite pour les frais d'inscription", verbose_name='Échéance inscription')),
                ('date_echeance_tranche_1', models.DateField(help_text='Date limite pour la 1ère tranche', verbose_name='Échéance 1ère tranche')),
                ('date_echeance_tranche_2', models.DateField(help_text='Date limite pour la 2ème tranche', verbose_name='Échéance 2ème tranche')),
                ('date_echeance_tranche_3', models.DateField(help_text='Date limite pour la 3ème tranche', verbose_name='Échéance 3ème tranche')),
                ('autoriser_paiement_partiel', models.BooleanField(default=True, verbose_name='Autoriser les paiements partiels')),
                ('penalite_retard', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pourcentage de pénalité appliqué en cas de retard', max_digits=5, verbose_name='Pénalité de retard (%)')),
                ('demande_inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='echeancier_prevu', to='inscription_ecoles.demandeinscriptionecole')),
            ],
            options={
                'verbose_name': "Échéancier d'inscription",
                'verbose_name_plural': "Échéanciers d'inscription",
            },
        ),
        migrations.CreateModel(
            name='ClasseInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la classe')),
                ('niveau', models.CharField(choices=[('GARDERIE', 'Garderie'), ('MATERNELLE', 'Maternelle'), ('PRIMAIRE_1', 'Primaire 1ère'), ('PRIMAIRE_2', 'Primaire 2ème'), ('PRIMAIRE_3', 'Primaire 3ème'), ('PRIMAIRE_4', 'Primaire 4ème'), ('PRIMAIRE_5', 'Primaire 5ème'), ('PRIMAIRE_6', 'Primaire 6ème'), ('COLLEGE_7', 'Collège 7ème'), ('COLLEGE_8', 'Collège 8ème'), ('COLLEGE_9', 'Collège 9ème'), ('COLLEGE_10', 'Collège 10ème'), ('LYCEE_11', 'Lycée 11ème'), ('LYCEE_12', 'Lycée 12ème'), ('TERMINALE', 'Terminale')], max_length=20, verbose_name='Niveau')),
                ('code_matricule', models.CharField(blank=True, help_text='Préfixe utilisé pour les matricules (ex: PN3, CN7, L11SL).', max_length=12, null=True, verbose_name='Code matricule')),
                ('capacite_max', models.PositiveIntegerField(default=30, verbose_name='Capacité maximale')),
                ('frais_inscription', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name="Frais d'inscription (GNF)")),
                ('tranche_1', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name='1ère tranche (GNF)')),
                ('tranche_2', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name='2ème tranche (GNF)')),
                ('tranche_3', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name='3ème tranche (GNF)')),
                ('demande_inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_prevues', to='inscription_ecoles.demandeinscriptionecole')),
            ],
            options={
                'verbose_name': "Classe d'inscription",
                'verbose_name_plural': "Classes d'inscription",
                'unique_together': {('demande_inscription', 'nom')},
            },
        ),
    ]
