# Generated by Django 5.2.3 on 2025-08-07 05:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('VALIDATION', 'Validation'), ('CONSULTATION', 'Consultation'), ('EXPORT', 'Export'), ('IMPRESSION', 'Impression')], max_length=20, verbose_name='Action')),
                ('type_objet', models.CharField(choices=[('ELEVE', 'Élève'), ('PAIEMENT', 'Paiement'), ('DEPENSE', 'Dépense'), ('RAPPORT', 'Rapport'), ('UTILISATEUR', 'Utilisateur'), ('SYSTEME', 'Système')], max_length=20, verbose_name="Type d'objet")),
                ('objet_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="ID de l'objet")),
                ('description', models.TextField(verbose_name='Description')),
                ('adresse_ip', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': 'Journal des activités',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='ParametreSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100, unique=True, verbose_name='Clé')),
                ('valeur', models.TextField(verbose_name='Valeur')),
                ('type_valeur', models.CharField(choices=[('STRING', 'Chaîne de caractères'), ('INTEGER', 'Nombre entier'), ('DECIMAL', 'Nombre décimal'), ('BOOLEAN', 'Booléen'), ('DATE', 'Date'), ('JSON', 'JSON')], max_length=10, verbose_name='Type de valeur')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètre système',
                'verbose_name_plural': 'Paramètres système',
                'ordering': ['cle'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('DIRECTEUR', 'Directeur'), ('COMPTABLE', 'Comptable'), ('SECRETAIRE', 'Secrétaire'), ('ENSEIGNANT', 'Enseignant'), ('SURVEILLANT', 'Surveillant')], max_length=20, verbose_name='Rôle')),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+224\\d{8,9}$', 'Format: +224XXXXXXXXX')], verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='utilisateurs/photos/', verbose_name='Photo')),
                ('peut_valider_paiements', models.BooleanField(default=False, verbose_name='Peut valider les paiements')),
                ('peut_valider_depenses', models.BooleanField(default=False, verbose_name='Peut valider les dépenses')),
                ('peut_generer_rapports', models.BooleanField(default=False, verbose_name='Peut générer des rapports')),
                ('peut_gerer_utilisateurs', models.BooleanField(default=False, verbose_name='Peut gérer les utilisateurs')),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='SessionUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='Clé de session')),
                ('adresse_ip', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('date_debut', models.DateTimeField(auto_now_add=True, verbose_name='Début de session')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin de session')),
                ('active', models.BooleanField(default=True, verbose_name='Session active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session utilisateur',
                'verbose_name_plural': 'Sessions utilisateurs',
                'ordering': ['-date_debut'],
            },
        ),
    ]
