# Generated by Django 5.2.3 on 2025-08-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_add_granular_permissions'),
        ('utilisateurs', '0002_profil_ecole'),
    ]

    operations = [
    ]
