# Generated by Django 5.2.5 on 2025-09-04 05:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0003_classe_code_matricule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatiereClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la matière')),
                ('coefficient', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Coefficient')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='eleves.classe')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres_classes', to='eleves.ecole')),
            ],
            options={
                'verbose_name': 'Matière de classe',
                'verbose_name_plural': 'Matières de classe',
                'indexes': [models.Index(fields=['ecole', 'classe'], name='notes_matie_ecole_i_454701_idx'), models.Index(fields=['classe', 'nom'], name='notes_matie_classe__9edbf6_idx')],
                'unique_together': {('classe', 'nom')},
            },
        ),
    ]
