# Generated by Django 5.2.5 on 2025-09-09 05:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaremeAppreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du barème')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ecole', models.ForeignKey(blank=True, help_text='Laisser vide pour un barème global', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baremes_appreciation', to='eleves.ecole')),
            ],
            options={
                'verbose_name': "Barème d'appréciation",
                'verbose_name_plural': "Barèmes d'appréciation",
            },
        ),
        migrations.CreateModel(
            name='BaremeMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(blank=True, help_text='Format: 2025-2026 (laisser vide pour toutes années)', max_length=9, null=True)),
                ('code_serie', models.CharField(db_index=True, help_text='Ex: COLLEGE, L11SL, L11SS, L11SSII, L12SS, L12SM, L12SE, TERMINALE', max_length=20)),
                ('nom_matiere', models.CharField(db_index=True, max_length=100)),
                ('coefficient', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baremes', to='eleves.ecole')),
            ],
            options={
                'verbose_name': 'Barème matière',
                'verbose_name_plural': 'Barèmes matières',
            },
        ),
        migrations.CreateModel(
            name='MatiereClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la matière')),
                ('coefficient', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Coefficient')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='eleves.classe')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres_classes', to='eleves.ecole')),
            ],
            options={
                'verbose_name': 'Matière de classe',
                'verbose_name_plural': 'Matières de classe',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=120, verbose_name='Titre')),
                ('date', models.DateField(blank=True, null=True)),
                ('trimestre', models.CharField(blank=True, help_text='Ex: T1, T2, T3', max_length=16, null=True)),
                ('coefficient', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('annee_scolaire', models.CharField(blank=True, help_text='2025-2026', max_length=9, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='eleves.classe')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_creees', to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='eleves.ecole')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='notes.matiereclasse')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(db_index=True, max_length=20)),
                ('note', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='eleves.classe')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='eleves.ecole')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='eleves.eleve')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.evaluation')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.matiereclasse')),
                ('saisie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='SeuilAppreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_min', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Note minimum')),
                ('appreciation', models.CharField(max_length=100, verbose_name='Appréciation')),
                ('couleur', models.CharField(blank=True, help_text='Code couleur hex (ex: #28a745)', max_length=7, null=True, verbose_name='Couleur')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('bareme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seuils', to='notes.baremeappreciation')),
            ],
            options={
                'verbose_name': "Seuil d'appréciation",
                'verbose_name_plural': "Seuils d'appréciation",
                'ordering': ['-note_min'],
            },
        ),
        migrations.AddIndex(
            model_name='baremeappreciation',
            index=models.Index(fields=['ecole', 'actif'], name='notes_barem_ecole_i_8024c1_idx'),
        ),
        migrations.AddIndex(
            model_name='baremematiere',
            index=models.Index(fields=['code_serie', 'nom_matiere'], name='notes_barem_code_se_221d02_idx'),
        ),
        migrations.AddIndex(
            model_name='baremematiere',
            index=models.Index(fields=['ecole', 'annee_scolaire'], name='notes_barem_ecole_i_f10e54_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='baremematiere',
            unique_together={('ecole', 'annee_scolaire', 'code_serie', 'nom_matiere')},
        ),
        migrations.AddIndex(
            model_name='matiereclasse',
            index=models.Index(fields=['ecole', 'classe'], name='notes_matie_ecole_i_454701_idx'),
        ),
        migrations.AddIndex(
            model_name='matiereclasse',
            index=models.Index(fields=['classe', 'nom'], name='notes_matie_classe__9edbf6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matiereclasse',
            unique_together={('classe', 'nom')},
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['ecole', 'classe', 'matiere'], name='notes_evalu_ecole_i_c3158a_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['annee_scolaire'], name='notes_evalu_annee_s_3b7dff_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['ecole', 'classe', 'matiere'], name='notes_note_ecole_i_47329a_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['evaluation'], name='notes_note_evaluat_2e6428_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['matricule'], name='notes_note_matricu_2b0005_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('evaluation', 'eleve')},
        ),
        migrations.AddIndex(
            model_name='seuilappreciation',
            index=models.Index(fields=['bareme', 'actif', '-note_min'], name='notes_seuil_bareme__dfef5a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seuilappreciation',
            unique_together={('bareme', 'note_min')},
        ),
    ]
