# Generated by Django 5.2.5 on 2025-09-04 10:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0003_classe_code_matricule_and_more'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaremeMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(blank=True, help_text='Format: 2025-2026 (laisser vide pour toutes années)', max_length=9, null=True)),
                ('code_serie', models.CharField(db_index=True, help_text='Ex: COLLEGE, L11SL, L11SS, L11SSII, L12SS, L12SM, L12SE, TERMINALE', max_length=20)),
                ('nom_matiere', models.CharField(db_index=True, max_length=100)),
                ('coefficient', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baremes', to='eleves.ecole')),
            ],
            options={
                'verbose_name': 'Barème matière',
                'verbose_name_plural': 'Barèmes matières',
                'indexes': [models.Index(fields=['code_serie', 'nom_matiere'], name='notes_barem_code_se_221d02_idx'), models.Index(fields=['ecole', 'annee_scolaire'], name='notes_barem_ecole_i_f10e54_idx')],
                'unique_together': {('ecole', 'annee_scolaire', 'code_serie', 'nom_matiere')},
            },
        ),
    ]
