# Generated by Django 5.2.5 on 2025-09-07 07:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0003_classe_code_matricule_and_more'),
        ('notes', '0003_evaluation_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaremeAppreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du barème')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ecole', models.ForeignKey(blank=True, help_text='Laisser vide pour un barème global', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baremes_appreciation', to='eleves.ecole')),
            ],
            options={
                'verbose_name': "Barème d'appréciation",
                'verbose_name_plural': "Barèmes d'appréciation",
            },
        ),
        migrations.CreateModel(
            name='SeuilAppreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_min', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Note minimum')),
                ('appreciation', models.CharField(max_length=100, verbose_name='Appréciation')),
                ('couleur', models.CharField(blank=True, help_text='Code couleur hex (ex: #28a745)', max_length=7, null=True, verbose_name='Couleur')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('bareme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seuils', to='notes.baremeappreciation')),
            ],
            options={
                'verbose_name': "Seuil d'appréciation",
                'verbose_name_plural': "Seuils d'appréciation",
                'ordering': ['-note_min'],
            },
        ),
        migrations.AddIndex(
            model_name='baremeappreciation',
            index=models.Index(fields=['ecole', 'actif'], name='notes_barem_ecole_i_8024c1_idx'),
        ),
        migrations.AddIndex(
            model_name='seuilappreciation',
            index=models.Index(fields=['bareme', 'actif', '-note_min'], name='notes_seuil_bareme__dfef5a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seuilappreciation',
            unique_together={('bareme', 'note_min')},
        ),
    ]
