# Generated by Django 5.2.5 on 2025-09-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_baremeappreciation_seuilappreciation_and_more'),
    ]

    operations = [
    ]
