# Generated by Django 5.2.5 on 2025-09-09 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableauBord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du tableau de bord')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('configuration', models.JSONField(default=dict, verbose_name='Configuration du tableau')),
                ('ordre_widgets', models.JSONField(default=list, verbose_name='Ordre des widgets')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('partage_avec', models.ManyToManyField(blank=True, related_name='tableaux_bord_partages', to=settings.AUTH_USER_MODEL)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableaux_bord', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tableau de bord',
                'verbose_name_plural': 'Tableaux de bord',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du rapport')),
                ('description', models.TextField(verbose_name='Description')),
                ('categorie', models.CharField(choices=[('FINANCIER', 'Financier'), ('PEDAGOGIQUE', 'Pédagogique'), ('ADMINISTRATIF', 'Administratif'), ('STATISTIQUE', 'Statistique')], max_length=20, verbose_name='Catégorie')),
                ('template_path', models.CharField(max_length=200, verbose_name='Chemin du template')),
                ('requete_sql', models.TextField(blank=True, null=True, verbose_name='Requête SQL personnalisée')),
                ('parametres_requis', models.JSONField(default=dict, verbose_name='Paramètres requis')),
                ('roles_autorises', models.JSONField(default=list, verbose_name='Rôles autorisés')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Type de rapport',
                'verbose_name_plural': 'Types de rapports',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du rapport')),
                ('parametres', models.JSONField(default=dict, verbose_name='Paramètres utilisés')),
                ('periode_debut', models.DateField(blank=True, null=True, verbose_name='Début de période')),
                ('periode_fin', models.DateField(blank=True, null=True, verbose_name='Fin de période')),
                ('format_rapport', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV'), ('HTML', 'HTML')], max_length=10, verbose_name='Format')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours de génération'), ('TERMINE', 'Terminé'), ('ERREUR', 'Erreur')], default='EN_COURS', max_length=20, verbose_name='Statut')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='rapports/', verbose_name='Fichier généré')),
                ('nombre_enregistrements', models.PositiveIntegerField(default=0, verbose_name="Nombre d'enregistrements")),
                ('taille_fichier', models.PositiveIntegerField(default=0, verbose_name='Taille du fichier (bytes)')),
                ('duree_generation', models.DurationField(blank=True, null=True, verbose_name='Durée de génération')),
                ('message_erreur', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_generation', models.DateTimeField(blank=True, null=True, verbose_name='Date de génération')),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('type_rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='rapports.typerapport')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ExportProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'export")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('frequence', models.CharField(choices=[('QUOTIDIEN', 'Quotidien'), ('HEBDOMADAIRE', 'Hebdomadaire'), ('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel')], max_length=20, verbose_name='Fréquence')),
                ('heure_execution', models.TimeField(verbose_name="Heure d'exécution")),
                ('jour_semaine', models.PositiveIntegerField(blank=True, help_text='Pour les exports hebdomadaires', null=True, verbose_name='Jour de la semaine (1=Lundi)')),
                ('jour_mois', models.PositiveIntegerField(blank=True, help_text='Pour les exports mensuels', null=True, verbose_name='Jour du mois')),
                ('emails_destinataires', models.JSONField(default=list, verbose_name='Emails des destinataires')),
                ('parametres', models.JSONField(default=dict, verbose_name='Paramètres du rapport')),
                ('format_export', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV'), ('HTML', 'HTML')], max_length=10, verbose_name="Format d'export")),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('TERMINE', 'Terminé')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('derniere_execution', models.DateTimeField(blank=True, null=True, verbose_name='Dernière exécution')),
                ('prochaine_execution', models.DateTimeField(blank=True, null=True, verbose_name='Prochaine exécution')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('type_rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports_programmes', to='rapports.typerapport')),
            ],
            options={
                'verbose_name': 'Export programmé',
                'verbose_name_plural': 'Exports programmés',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du widget')),
                ('type_widget', models.CharField(choices=[('GRAPHIQUE_LIGNE', 'Graphique en ligne'), ('GRAPHIQUE_BARRE', 'Graphique en barres'), ('GRAPHIQUE_SECTEUR', 'Graphique en secteurs'), ('TABLEAU', 'Tableau'), ('INDICATEUR', 'Indicateur'), ('JAUGE', 'Jauge'), ('LISTE', 'Liste')], max_length=20, verbose_name='Type de widget')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre affiché')),
                ('requete_sql', models.TextField(verbose_name='Requête SQL')),
                ('configuration', models.JSONField(default=dict, verbose_name='Configuration du widget')),
                ('position_x', models.PositiveIntegerField(default=0, verbose_name='Position X')),
                ('position_y', models.PositiveIntegerField(default=0, verbose_name='Position Y')),
                ('largeur', models.PositiveIntegerField(default=4, verbose_name='Largeur (colonnes)')),
                ('hauteur', models.PositiveIntegerField(default=3, verbose_name='Hauteur (lignes)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tableau_bord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='rapports.tableaubord')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['tableau_bord', 'position_y', 'position_x'],
            },
        ),
    ]
