# Generated by Django 5.2.3 on 2025-08-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='heures_mensuelles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Nombre d'heures de travail prévues par mois (pour calcul précis du salaire)", max_digits=6, null=True, verbose_name='Heures mensuelles'),
        ),
    ]
