# Generated by Django 5.2.5 on 2025-09-09 05:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonnementBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('periodicite', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('ANNUEL', 'Annuel'), ('T1', '1ère Tranche'), ('T2', '2ème Tranche'), ('T3', '3ème Tranche')], default='MENSUEL', max_length=10)),
                ('date_debut', models.DateField(default=django.utils.timezone.localdate)),
                ('date_expiration', models.DateField(db_index=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('SUSPENDU', 'Suspendu')], db_index=True, default='ACTIF', max_length=10)),
                ('alerte_avant_jours', models.PositiveIntegerField(default=7)),
                ('derniere_relance', models.DateTimeField(blank=True, null=True)),
                ('zone', models.CharField(blank=True, max_length=100)),
                ('itineraire', models.CharField(blank=True, max_length=200)),
                ('point_arret', models.CharField(blank=True, max_length=150)),
                ('contact_parent', models.CharField(blank=True, max_length=100)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements_bus', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Abonnement bus',
                'verbose_name_plural': 'Abonnements bus',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['eleve', 'statut'], name='bus_abonnem_eleve_i_edaaea_idx'), models.Index(fields=['eleve', 'date_expiration'], name='bus_abonnem_eleve_i_7c4ed5_idx'), models.Index(fields=['statut', 'date_expiration'], name='bus_abonnem_statut_a59a9d_idx')],
            },
        ),
    ]
