# Generated by Django 5.2.3 on 2025-08-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
        ('eleves', '0002_alter_eleve_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnementbus',
            name='date_expiration',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='abonnementbus',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('SUSPENDU', 'Suspendu')], db_index=True, default='ACTIF', max_length=10),
        ),
        migrations.AddIndex(
            model_name='abonnementbus',
            index=models.Index(fields=['eleve', 'statut'], name='bus_abonnem_eleve_i_edaaea_idx'),
        ),
        migrations.AddIndex(
            model_name='abonnementbus',
            index=models.Index(fields=['eleve', 'date_expiration'], name='bus_abonnem_eleve_i_7c4ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='abonnementbus',
            index=models.Index(fields=['statut', 'date_expiration'], name='bus_abonnem_statut_a59a9d_idx'),
        ),
    ]
